In [32]:
import pandas as pd
import numpy as np

from mlxtend.frequent_patterns import apriori, association_rules
import ipywidgets as widgets
from ipywidgets import interact
from tqdm import tqdm 
import warnings
warnings.filterwarnings("ignore")

In [21]:
fp_df = pd.read_csv("Datasets/Faceplate.csv", index_col=0)
fp_df

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0
6              0      1     1       0      0       0
7              1      0     1       0      0       0
8              1      1     1       0      1       0
9              1      1     1       0      0       0
10             0      0     0       0      0       1

In [30]:
fp_df = fp_df.astype(bool)
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)

rules = association_rules(itemsets, metric='confidence', min_threshold=0.6)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

relv_rules = rules[rules['lift']>1]
relv_rules.sort_values('lift', ascending = False)

,antecedents,consequents,support,confidence,lift
9,frozenset({Green}),"frozenset({White, Red})",0.2,1.000000,2.500000
3,frozenset({Green}),frozenset({Red}),0.2,1.000000,1.666667
7,"frozenset({Green, White})",frozenset({Red}),0.2,1.000000,1.666667
5,frozenset({Orange}),frozenset({White}),0.2,1.000000,1.428571
6,frozenset({Green}),frozenset({White}),0.2,1.000000,1.428571
8,"frozenset({Green, Red})",frozenset({White}),0.2,1.000000,1.428571
1,frozenset({Blue}),frozenset({Red}),0.4,0.666667,1.111111
2,frozenset({Red}),frozenset({Blue}),0.4,0.666667,1.111111

# Cosmetics Dataset

In [28]:
cosm = pd.read_csv("Datasets/Cosmetics.csv", index_col=0)
cosm

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,0,1,1,1,1,0,1,1,1,0,0,0,0,1
2,0,0,1,0,1,0,1,1,0,0,1,1,0,0
3,0,1,0,0,1,1,1,1,1,1,1,1,1,0
4,0,0,1,1,1,0,1,0,0,0,1,0,0,1
5,0,1,0,0,1,0,1,1,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,1,1,0,0
998,0,1,1,1,1,0,0,1,0,0,1,0,1,1
999,1,1,0,0,1,0,0,0,1,1,0,0,1,1
1000,0,0,0,0,1,0,1,1,0,1,0,0,0,1

In [31]:
itemsets = apriori(cosm, min_support=0.2, use_colnames=True)

rules = association_rules(itemsets, metric='confidence', min_threshold=0.6)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

relv_rules = rules[rules['lift']>1]
relv_rules.sort_values('lift', ascending = False)

,antecedents,consequents,support,confidence,lift
3,frozenset({Eye shadow}),frozenset({Mascara}),0.321,0.842520,2.359999
4,frozenset({Mascara}),frozenset({Eye shadow}),0.321,0.899160,2.359999
1,frozenset({Concealer}),frozenset({Eyeliner}),0.297,0.671946,1.470341
2,frozenset({Eyeliner}),frozenset({Concealer}),0.297,0.649891,1.470341
0,frozenset({Blush}),frozenset({Concealer}),0.220,0.606061,1.371178
5,frozenset({Foundation}),frozenset({Lip Gloss}),0.356,0.664179,1.355468
6,frozenset({Lip Gloss}),frozenset({Foundation}),0.356,0.726531,1.355468

In [40]:
def gen_rules(permissible_support, confidence_threshold):
    itemsets = apriori(cosm, min_support=0.2, use_colnames=True)

    rules = association_rules(itemsets, metric='confidence', min_threshold=0.6)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

    relv_rules = rules[rules['lift']>1]
    return relv_rules.sort_values('lift', ascending = False)

In [41]:
interact(gen_rules, 
        permissible_support = widgets.FloatSlider(value=0.3, min=0.01, max=1, step=0.01,
                                                 description="Minimum Support:"),
         confidence_threshold = widgets.FloatSlider(value=0.3, min=0.01, max=1, step=0.01,
                                                 description="Confidence Threshold:"))

interactive(children=(FloatSlider(value=0.3, description='Minimum Support:', max=1.0, min=0.01, step=0.01), Fl…