In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, KFold, cross_val_score  #***
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import  ColumnTransformer, make_column_transformer, make_column_selector
from sklearn.metrics import r2_score, log_loss, accuracy_score, roc_auc_score, f1_score, log_loss

from sklearn.tree import DecisionTreeRegressor, plot_tree, DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression, ElasticNet, Ridge
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from xgboost import XGBClassifier, XGBRegressor
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, StackingClassifier, StackingRegressor

from tqdm import tqdm  # Provides the progress of model running
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
concrete = pd.read_csv('D:/Machine_Learning/Cases/Concrete_Strength/Concrete_Data.csv')
X , y = concrete.drop(['Strength'], axis=1), concrete['Strength']

lr = LinearRegression()
kfold = KFold(n_splits=5, shuffle=True, random_state=26)
results = cross_val_score(lr, X, y, cv=kfold)  # Finds r2_score by default
print(results)
print(np.mean(results))

[0.61474372 0.56604898 0.59335131 0.61186382 0.62837728]
0.602877022245518

In [13]:

alphas = np.linspace(0.001, 10, 30)
scores=[]
for a in tqdm(alphas):
    ridge = Ridge(alpha=a)
    kfold = KFold(n_splits=5, shuffle=True, random_state=26) 
    scores.append([a, cross_val_score(ridge, X, y, cv=kfold).mean()])
    
df_scores = pd.DataFrame(scores, columns=['alpha', 'cross_val_score' ])
df_scores.sort_values(['cross_val_score'], ascending=False).head()

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 32.60it/s]

        alpha  cross_val_score
29  10.000000         0.602878
28   9.655207         0.602878
27   9.310414         0.602878
26   8.965621         0.602878
25   8.620828         0.602878

In [15]:
alphas = np.linspace(0.001, 10, 30)
scores=[]
for a in tqdm(alphas):
    ridge = Ridge(alpha=a)
    results = cross_val_score(ridge, X, y, cv=kfold) 
    scores.append([a, np.mean(results)])
    print(results)
    
df_scores = pd.DataFrame(scores, columns=['alpha', 'cross_val_score' ])
df_scores.sort_values(['cross_val_score'], ascending=False).head()

 23%|███████████████████▎                                                               | 7/30 [00:00<00:00, 31.88it/s]

[0.61474372 0.56604898 0.59335131 0.61186383 0.62837728]
[0.61474377 0.56604882 0.59335126 0.61186417 0.62837729]
[0.61474383 0.56604866 0.59335121 0.61186452 0.62837729]
[0.61474389 0.5660485  0.59335115 0.61186486 0.6283773 ]
[0.61474395 0.56604835 0.5933511  0.61186521 0.6283773 ]
[0.61474401 0.56604819 0.59335105 0.61186555 0.62837731]
[0.61474406 0.56604803 0.593351   0.6118659  0.62837731]

 47%|██████████████████████████████████████▎                                           | 14/30 [00:00<00:00, 28.18it/s]

[0.61474412 0.56604787 0.59335094 0.61186624 0.62837732]
[0.61474418 0.56604772 0.59335089 0.61186659 0.62837732]
[0.61474424 0.56604756 0.59335084 0.61186693 0.62837733]
[0.6147443  0.5660474  0.59335079 0.61186728 0.62837734]
[0.61474435 0.56604724 0.59335073 0.61186762 0.62837734]
[0.61474441 0.56604708 0.59335068 0.61186797 0.62837735]
[0.61474447 0.56604693 0.59335063 0.61186831 0.62837735]

 70%|█████████████████████████████████████████████████████████▍                        | 21/30 [00:00<00:00, 31.09it/s]

[0.61474453 0.56604677 0.59335058 0.61186866 0.62837736]
[0.61474459 0.56604661 0.59335053 0.611869   0.62837736]
[0.61474464 0.56604645 0.59335047 0.61186935 0.62837737]
[0.6147447  0.56604629 0.59335042 0.61186969 0.62837737]
[0.61474476 0.56604614 0.59335037 0.61187004 0.62837738]
[0.61474482 0.56604598 0.59335032 0.61187038 0.62837738]
[0.61474488 0.56604582 0.59335026 0.61187073 0.62837739]

 97%|███████████████████████████████████████████████████████████████████████████████▎  | 29/30 [00:00<00:00, 30.88it/s]

[0.61474493 0.56604566 0.59335021 0.61187107 0.62837739]
[0.61474499 0.56604551 0.59335016 0.61187142 0.6283774 ]
[0.61474505 0.56604535 0.59335011 0.61187176 0.6283774 ]
[0.61474511 0.56604519 0.59335005 0.61187211 0.62837741]
[0.61474516 0.56604503 0.59335    0.61187245 0.62837741]
[0.61474522 0.56604488 0.59334995 0.61187279 0.62837742]
[0.61474528 0.56604472 0.5933499  0.61187314 0.62837742]
[0.61474534 0.56604456 0.59334984 0.61187348 0.62837743]

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 29.43it/s]

[0.6147454  0.5660444  0.59334979 0.61187383 0.62837743]

        alpha  cross_val_score
29  10.000000         0.602878
28   9.655207         0.602878
27   9.310414         0.602878
26   8.965621         0.602878
25   8.620828         0.602878

In [16]:
alphas = np.linspace(0.001, 10, 30)
ratios = np.linspace(0.001,1,10) 
scores=[]
for a in tqdm(alphas):
    for r in ratios:
        el = ElasticNet(alpha=a, l1_ratio=r)
        results = cross_val_score(el, X, y, cv=kfold) 
        scores.append([a, r, np.mean(results)])
        print(results)

  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[0.61474385 0.5660486  0.59335119 0.61186465 0.62837729]
[0.61474388 0.5660484  0.59335115 0.61186479 0.62837729]
[0.61474391 0.56604819 0.59335112 0.61186493 0.62837729]
[0.61474395 0.56604799 0.59335109 0.61186507 0.62837729]
[0.61474398 0.56604779 0.59335105 0.61186521 0.62837729]
[0.61474401 0.56604759 0.59335102 0.61186535 0.62837729]
[0.61474404 0.56604738 0.59335099 0.61186549 0.62837729]

  3%|██▊                                                                                | 1/30 [00:00<00:10,  2.85it/s]

[0.61474407 0.56604718 0.59335095 0.61186563 0.62837729]
[0.6147441  0.56604698 0.59335092 0.61186577 0.62837729]
[0.61474413 0.56604677 0.59335088 0.6118659  0.62837729]
[0.61478869 0.56592152 0.59330686 0.61213675 0.62837837]
[0.61479801 0.56585164 0.59329418 0.6121829  0.62837672]
[0.61480712 0.56578081 0.59328109 0.61222904 0.62837475]
[0.61481602 0.56570911 0.59326757 0.61227515 0.62837245]

  7%|█████▌                                                                             | 2/30 [00:00<00:09,  2.97it/s]

[0.61482467 0.56563641 0.59325366 0.61232126 0.62836986]
[0.61483314 0.56556272 0.59323927 0.61236733 0.6283669 ]
[0.61484135 0.56548809 0.59322447 0.61241339 0.62836363]
[0.61484937 0.56541256 0.5932092  0.61245945 0.62835999]
[0.61485713 0.56533599 0.59319349 0.61250545 0.62835603]
[0.61486473 0.56525836 0.59317734 0.6125514  0.62835173]
[0.6148279  0.56580149 0.59326071 0.61238496 0.62837341]
[0.61484439 0.56566251 0.59323333 0.61247328 0.62836731]
[0.61486006 0.56551987 0.59320432 0.61256147 0.62835996]
[0.61487483 0.56537367 0.59317359 0.6126495  0.62835128]
[0.61488871 0.56522358 0.59314111 0.61273741 0.62834123]
[0.61490154 0.56506957 0.59310682 0.6128251  0.62832979]
[0.61491353 0.56491189 0.59307074 0.61291261 0.62831696]
[0.61492448 0.56474974 0.5930327  0.61299988 0.6283026 ]
[0.61493433 0.56458358 0.59299273 0.61308692 0.62828673]

 10%|████████▎                                                                          | 3/30 [00:01<00:09,  2.99it/s]

[0.61494305 0.564413   0.59295078 0.61317365 0.62826931]
[0.6148622  0.56568806 0.59321318 0.612612   0.62836327]
[0.61488399 0.56548063 0.5931693  0.61273887 0.62835023]
[0.61490384 0.56526538 0.5931217  0.61286532 0.62833433]
[0.61492163 0.56504206 0.59307027 0.61299128 0.62831541]
[0.61493728 0.56481008 0.59301491 0.61311668 0.62829332]
[0.61495068 0.56456922 0.59295528 0.61324151 0.62826792]

 13%|███████████                                                                        | 4/30 [00:01<00:08,  3.02it/s]

[0.61496179 0.56431927 0.59289123 0.61336558 0.62823914]
[0.61497035 0.56406    0.59282267 0.61348888 0.62820666]
[0.61497621 0.56379068 0.59274939 0.61361132 0.62817041]
[0.6149795  0.56351092 0.59267117 0.6137328  0.62813002]
[0.61489225 0.56558077 0.59316463 0.61282019 0.62834869]
[0.61491762 0.56530581 0.59310268 0.61298224 0.62832646]
[0.61493949 0.56501726 0.59303418 0.61314333 0.62829913]

 17%|█████████████▊                                                                     | 5/30 [00:01<00:08,  3.05it/s]

[0.61495773 0.56471426 0.59295883 0.6133033  0.62826623]
[0.61497192 0.56439652 0.59287619 0.61346198 0.62822772]
[0.61498188 0.56406261 0.59278587 0.61361918 0.62818296]
[0.61498719 0.56371216 0.59268753 0.61377474 0.62813159]
[0.61498807 0.56334448 0.59258051 0.61392836 0.62807332]
[0.61498349 0.56295752 0.59246443 0.61407977 0.62800767]
[0.61497332 0.56255143 0.59233855 0.6142288  0.62793416]
[0.61491857 0.56547924 0.59311537 0.61301154 0.62833032]
[0.61494599 0.56513767 0.59303399 0.61320567 0.62829689]
[0.61496789 0.56477539 0.59294246 0.61339795 0.62825537]
[0.61498394 0.56439092 0.59284018 0.61358813 0.62820525]
[0.61499347 0.56398339 0.59272635 0.61377583 0.6281458 ]
[0.61499606 0.56355055 0.59260016 0.61396068 0.62807634]
[0.61499128 0.56309132 0.59246068 0.61414221 0.62799618]
[0.61497828 0.56260348 0.59230709 0.61431997 0.62790425]

 20%|████████████████▌                                                                  | 6/30 [00:01<00:07,  3.11it/s]

[0.61495675 0.56208587 0.59213832 0.61449339 0.62779954]
[0.61492528 0.56153504 0.5919532  0.6146618  0.62768138]
[0.61494163 0.5653831  0.59306564 0.61318781 0.62830868]
[0.61496975 0.56497584 0.59296363 0.61341108 0.62826229]
[0.61498986 0.56453951 0.59284716 0.61363134 0.62820426]
[0.61500135 0.56407212 0.59271516 0.61384801 0.62813352]
[0.61500319 0.56357086 0.59256629 0.61406054 0.62804914]
[0.6149949  0.563034   0.59239918 0.6142682  0.62794978]

 23%|███████████████████▎                                                               | 7/30 [00:02<00:07,  3.25it/s]

[0.61497476 0.56245728 0.59221221 0.61447015 0.62783416]
[0.61494266 0.56183966 0.59200382 0.6146655  0.62770048]
[0.61489639 0.56117576 0.59177208 0.61485315 0.62754696]
[0.61483487 0.56046162 0.59151485 0.61503184 0.62737206]
[0.61496182 0.56529199 0.59301565 0.61335052 0.62828424]
[0.61498939 0.56482017 0.59289202 0.61360024 0.62822325]
[0.61500613 0.56430976 0.5927489  0.61384535 0.62814634]

 27%|██████████████████████▏                                                            | 8/30 [00:02<00:06,  3.22it/s]

[0.61501064 0.56375769 0.59258461 0.61408505 0.62805222]
[0.61500213 0.56315986 0.5923969  0.61431829 0.62793897]
[0.61497867 0.56251329 0.59218396 0.6145439  0.62780463]
[0.61493904 0.56181189 0.59194328 0.61476051 0.62764683]
[0.61488116 0.56105219 0.59167175 0.61496653 0.62746318]
[0.61480294 0.56022717 0.59136643 0.61516007 0.62725075]
[0.61470258 0.55933176 0.59102371 0.61533894 0.62700618]
[0.6149795  0.5652056  0.59296558 0.61350102 0.62825739]
[0.61500544 0.56467026 0.59281947 0.61377468 0.62818032]
[0.61501702 0.56408608 0.59264804 0.61404179 0.62808268]
[0.6150128  0.5634477  0.59244905 0.61430104 0.62796211]
[0.61499095 0.562751   0.59221944 0.61455096 0.62781623]
[0.61494896 0.56198909 0.59195596 0.61478971 0.62764192]
[0.61488482 0.56115543 0.59165472 0.61501511 0.62743568]

 30%|████████████████████████▉                                                          | 9/30 [00:02<00:06,  3.16it/s]

[0.61479542 0.56024269 0.59131166 0.61522461 0.62719394]
[0.61467754 0.55924193 0.59092208 0.61541515 0.62691165]
[0.61452747 0.5581434  0.59047978 0.61558308 0.62658373]
[0.61499495 0.56512363 0.59291555 0.61364046 0.62822846]
[0.61501827 0.56452603 0.59274616 0.61393576 0.62813403]
[0.61502339 0.56386773 0.59254527 0.6142221  0.6280137 ]
[0.61500831 0.56314275 0.59230923 0.61449774 0.62786419]

 33%|███████████████████████████▎                                                      | 10/30 [00:03<00:06,  3.21it/s]

[0.61497044 0.56234343 0.59203429 0.6147604  0.62768209]
[0.61490635 0.56146198 0.59171566 0.61500747 0.62746302]
[0.61481299 0.56048871 0.59134782 0.61523571 0.62720215]
[0.61468591 0.55941239 0.59092503 0.61544119 0.62689343]
[0.61452036 0.55822075 0.59043943 0.61561928 0.62653022]
[0.6143101  0.55689841 0.58988299 0.61576427 0.62610468]
[0.61500844 0.56504581 0.59286569 0.61376989 0.62819776]
[0.61502821 0.56438706 0.59267239 0.61408466 0.62808483]
[0.61502555 0.56365523 0.5924405  0.6143877  0.6279401 ]
[0.61499805 0.56284243 0.5921657  0.6146766  0.62775922]
[0.61494131 0.56193862 0.59184237 0.61494822 0.62753752]
[0.61485165 0.56093242 0.59146416 0.61519886 0.627269  ]
[0.6147244  0.55981164 0.59102356 0.61542395 0.62694696]
[0.61455346 0.55856156 0.59051227 0.61561777 0.62656293]
[0.61433138 0.55716286 0.58991963 0.61577353 0.62610758]

 37%|██████████████████████████████                                                    | 11/30 [00:03<00:06,  3.13it/s]

[0.61405051 0.5563277  0.58923333 0.61588256 0.62556903]
[0.61502018 0.56497189 0.59281609 0.61389022 0.62816553]
[0.61503559 0.56425312 0.59259835 0.61422247 0.62803309]
[0.61502417 0.5634481  0.59233451 0.61453982 0.6278624 ]
[0.614982   0.56254674 0.59201894 0.614839   0.62764789]
[0.61490423 0.56153621 0.59164407 0.61511592 0.62738334]
[0.61478614 0.56040201 0.59120203 0.61536547 0.62706086]
[0.61461993 0.55912712 0.59068283 0.61558138 0.62667117]

 40%|████████████████████████████████▊                                                 | 12/30 [00:03<00:05,  3.16it/s]

[0.61439887 0.55769093 0.59007453 0.61575568 0.62620348]
[0.61411237 0.55634804 0.58936284 0.61587861 0.62564409]
[0.61374895 0.5563675  0.58853099 0.615938   0.62497676]
[0.61503039 0.56490164 0.59276682 0.61400227 0.62813199]
[0.61504068 0.56412396 0.59252409 0.61435015 0.62797913]
[0.61501917 0.5632466  0.59222744 0.61467954 0.62778091]
[0.6149609  0.56225561 0.59186913 0.61498623 0.62753082]

 43%|███████████████████████████████████▌                                              | 13/30 [00:04<00:05,  3.14it/s]

[0.61486025 0.5611364  0.59144048 0.61526487 0.62722012]
[0.61470955 0.55986937 0.59093054 0.61550874 0.62683932]
[0.61450033 0.55843415 0.59032654 0.61570947 0.62637624]
[0.61422223 0.55680202 0.58961271 0.61585625 0.62581606]
[0.61386267 0.55638683 0.58877042 0.61593552 0.6251408 ]
[0.61340483 0.55640507 0.58777561 0.61593044 0.624328  ]
[0.61503921 0.56483482 0.59271795 0.61410675 0.62809734]
[0.61504387 0.56399936 0.59244998 0.61446854 0.62792325]

 47%|██████████████████████████████████████▎                                           | 14/30 [00:04<00:04,  3.27it/s]

[0.61501135 0.56304972 0.59211933 0.61480786 0.62769635]
[0.6149356  0.56196905 0.59171713 0.61511941 0.62740833]
[0.61480953 0.56073941 0.59123163 0.61539637 0.62704901]
[0.61462362 0.55933599 0.59065014 0.61563012 0.62660566]
[0.61436702 0.55773255 0.58995547 0.6158096  0.62606293]
[0.61402564 0.55640221 0.58912787 0.61592058 0.62540181]
[0.61358363 0.55642322 0.5881422  0.61594519 0.62459824]
[0.61301881 0.5564375  0.58745588 0.61585997 0.62383236]
[0.61504682 0.56477124 0.59266953 0.61420431 0.62806174]
[0.61504509 0.56387938 0.59237588 0.61457843 0.62786558]
[0.61500079 0.56285767 0.59201078 0.61492571 0.62760876]
[0.61490614 0.56168774 0.5915628  0.61523957 0.62728114]
[0.61475209 0.56034544 0.59101856 0.61551154 0.62687022]
[0.61452788 0.55880216 0.59036116 0.61573073 0.62636047]
[0.6142195  0.5570259  0.58957042 0.61588308 0.62573214]
[0.61380919 0.55643793 0.58862055 0.61595025 0.62496129]

 50%|█████████████████████████████████████████                                         | 15/30 [00:04<00:04,  3.26it/s]

[0.61327512 0.55645518 0.58748085 0.61590829 0.62401722]
[0.61280632 0.55646777 0.58738269 0.61572631 0.62369672]
[0.61505333 0.56471071 0.59262159 0.61429552 0.62802533]
[0.61504483 0.56376329 0.59230215 0.61468049 0.62780656]
[0.61498744 0.56267087 0.59190157 0.61503386 0.62751881]
[0.6148729  0.56141028 0.59140666 0.61534767 0.6271499 ]
[0.61468937 0.55995452 0.59080114 0.61561151 0.6266848 ]
[0.61442402 0.55826851 0.59006482 0.61581195 0.62610429]

 53%|███████████████████████████████████████████▋                                      | 16/30 [00:05<00:04,  3.35it/s]

[0.61405893 0.5565071  0.5891721  0.61593118 0.62538477]
[0.61357285 0.55646977 0.58809151 0.61594602 0.62449572]
[0.61293807 0.55648552 0.587418   0.61582611 0.62373592]
[0.61275454 0.55649302 0.58730321 0.61553664 0.62355533]
[0.61505887 0.56465306 0.59257417 0.6143809  0.62798824]
[0.61504294 0.56365143 0.59222861 0.61477537 0.62774617]
[0.61497215 0.5624887  0.59179206 0.61513308 0.62742642]
[0.61483576 0.56113801 0.59124899 0.61544453 0.62701461]

 57%|██████████████████████████████████████████████▍                                   | 17/30 [00:05<00:03,  3.31it/s]

[0.61462132 0.55956674 0.59058007 0.61569727 0.62649283]
[0.6143114  0.55773443 0.58976102 0.61587466 0.62583825]
[0.61388608 0.55648184 0.58876122 0.61595507 0.62502162]
[0.61331803 0.55650048 0.58754142 0.61590932 0.62400577]
[0.61281675 0.5565115  0.58735018 0.61569872 0.62361015]
[0.6126987  0.55651604 0.58721744 0.61543813 0.62340834]
[0.61506353 0.56459811 0.5925273  0.61446091 0.62795058]
[0.61503992 0.56354337 0.59215546 0.61486359 0.62768469]
[0.61495483 0.56231043 0.5916824  0.61522402 0.62733202]
[0.61479587 0.56086934 0.59109004 0.615531   0.62687584]
[0.61454777 0.55918231 0.59035603 0.61576961 0.62629506]
[0.6141918  0.55720088 0.58945095 0.61592017 0.62556256]
[0.61370147 0.55651144 0.5883384  0.61595588 0.62464347]
[0.6130448  0.55652881 0.58740706 0.61584132 0.62368504]
[0.61277106 0.55653591 0.58727754 0.61553145 0.62348004]
[0.61263722 0.55653533 0.58712503 0.61537271 0.62325566]

 60%|█████████████████████████████████████████████████▏                                | 18/30 [00:05<00:03,  3.29it/s]

[0.61506741 0.56454572 0.59248098 0.61453597 0.62791244]
[0.61503572 0.56343862 0.59208291 0.61494568 0.62762226]
[0.61493568 0.562137   0.5915727  0.6153073  0.62723585]
[0.61475307 0.56060575 0.59093033 0.61560777 0.62673393]
[0.6144702  0.55880121 0.59012873 0.61582956 0.62609217]
[0.61406431 0.55666745 0.58913479 0.61594913 0.62527827]
[0.6135058  0.55654075 0.5879046  0.6159344  0.62425104]
[0.61285322 0.55655336 0.58734756 0.61574249 0.62357166]

 63%|███████████████████████████████████████████████████▉                              | 19/30 [00:05<00:03,  3.33it/s]

[0.61272241 0.55655718 0.58719987 0.61544431 0.62334535]
[0.61258852 0.55654963 0.58704672 0.61530398 0.62309726]
[0.61507058 0.56449574 0.59243523 0.61460646 0.62787392]
[0.61503047 0.56333764 0.59201071 0.6150221  0.62755917]
[0.61491486 0.5619677  0.59146308 0.61538347 0.62713813]
[0.61470761 0.56034556 0.59076944 0.61567551 0.62658918]
[0.61438838 0.5584226  0.58989879 0.61587784 0.62588414]
[0.61393076 0.5566348  0.58881261 0.6159626  0.62498552]

 67%|██████████████████████████████████████████████████████▋                           | 20/30 [00:06<00:02,  3.39it/s]

[0.61329874 0.55656675 0.58746004 0.61589224 0.62384519]
[0.61281529 0.55657671 0.58728366 0.61561412 0.6234548 ]
[0.61266919 0.55657403 0.5871171  0.61536649 0.62320625]
[0.61254552 0.5565618  0.58698628 0.61523122 0.62293313]
[0.61507313 0.56444805 0.59239007 0.61467271 0.62783507]
[0.61502427 0.56323996 0.59193903 0.61509325 0.62749526]
[0.61489254 0.56180238 0.59135361 0.61545303 0.62703902]

 70%|█████████████████████████████████████████████████████████▍                        | 21/30 [00:06<00:02,  3.34it/s]

[0.6146597  0.56009037 0.59060785 0.61573482 0.62644211]
[0.61430259 0.55804866 0.58966651 0.61591514 0.62567159]
[0.61379018 0.55661604 0.58848555 0.61596167 0.62468524]
[0.61308269 0.55659217 0.58737188 0.61582978 0.62358035]
[0.61277456 0.55659763 0.58721663 0.61549387 0.62333467]
[0.61261189 0.55658953 0.58702967 0.61530404 0.6230625 ]
[0.61249901 0.55656863 0.58692248 0.61515352 0.62276921]
[0.6150751  0.5644025  0.59234549 0.61473503 0.62779597]
[0.61501721 0.56314542 0.59186792 0.61515952 0.62743076]
[0.61486883 0.56164093 0.59124439 0.61551643 0.62693871]
[0.61460955 0.55983934 0.59044572 0.61578626 0.62629248]
[0.61421315 0.55767725 0.58943249 0.615942   0.62545486]
[0.61364442 0.55660266 0.5881536  0.61594669 0.62437771]
[0.61288447 0.55661557 0.58731884 0.6157483  0.62347801]
[0.61273136 0.55661484 0.58714548 0.61541567 0.62321081]

 73%|████████████████████████████████████████████████████████████▏                     | 22/30 [00:06<00:02,  3.33it/s]

[0.61257135 0.55660183 0.58696359 0.61523831 0.62291441]
[0.61244909 0.55657362 0.58685521 0.61507275 0.62260552]
[0.61507655 0.564359   0.59230149 0.61479371 0.62775668]
[0.61500938 0.5630539  0.59179739 0.61522125 0.62736578]
[0.61484388 0.5614832  0.59113548 0.61557411 0.62683732]
[0.61455733 0.55959142 0.59028317 0.61583034 0.62614077]
[0.61412033 0.55730973 0.58919626 0.61595933 0.62523428]
[0.61349236 0.55662699 0.58781714 0.61591862 0.62406319]

 77%|██████████████████████████████████████████████████████████████▊                   | 23/30 [00:07<00:02,  3.43it/s]

[0.61285326 0.55663708 0.58726291 0.61564839 0.62337336]
[0.6126843  0.556631   0.58707039 0.61533352 0.62308365]
[0.61253038 0.55660963 0.58690501 0.6151684  0.62276181]
[0.61239296 0.5565749  0.58678751 0.6149879  0.62243849]
[0.61507753 0.56431742 0.59225808 0.614849   0.62771724]
[0.61500085 0.56296523 0.59172747 0.61527876 0.62730039]
[0.61481778 0.56132912 0.59102694 0.61562644 0.62673501]

 80%|█████████████████████████████████████████████████████████████████▌                | 24/30 [00:07<00:01,  3.38it/s]

[0.6145032  0.55934825 0.59012034 0.61586752 0.62598717]
[0.61402434 0.55694525 0.58895839 0.61596758 0.6250104 ]
[0.61333505 0.55665103 0.58747647 0.61587816 0.6237425 ]
[0.61281968 0.55665531 0.58720406 0.61553076 0.62326589]
[0.61263375 0.55664463 0.58699152 0.61527444 0.62295312]
[0.61248373 0.55661606 0.58684354 0.61509605 0.62260987]
[0.61233615 0.55657073 0.58671302 0.61489896 0.62226877]
[0.6150781  0.56427768 0.59221526 0.61490113 0.62767769]

 83%|████████████████████████████████████████████████████████████████████▎             | 25/30 [00:07<00:01,  3.49it/s]

[0.61499168 0.5628793  0.59165818 0.61533233 0.62723467]
[0.61479064 0.5611785  0.59091881 0.61567378 0.62663188]
[0.61444732 0.5591089  0.58995732 0.61589825 0.62583163]
[0.61392467 0.55684503 0.58871906 0.61596706 0.62478303]
[0.6131729  0.55667362 0.58733195 0.61582599 0.62345567]
[0.61278308 0.55667305 0.58714273 0.61545252 0.62315611]
[0.61258154 0.55665438 0.58690739 0.61521344 0.622819  ]
[0.61243715 0.55661941 0.58678223 0.6150204  0.6224587 ]
[0.61227577 0.55656485 0.58663504 0.61480495 0.62209509]
[0.61507828 0.56423966 0.59217301 0.61495031 0.62763808]
[0.61498193 0.56279601 0.59158928 0.61538221 0.62716868]
[0.61476301 0.56103122 0.59081115 0.61571645 0.62652805]
[0.61439044 0.5588723  0.58979423 0.61592293 0.6256748 ]
[0.61382298 0.55683908 0.58847846 0.61595867 0.62455265]
[0.61300619 0.55669334 0.58728551 0.61576277 0.62336529]
[0.61274542 0.55668873 0.587078   0.61538414 0.62304375]
[0.61254457 0.5566632  0.58685588 0.61515065 0.62268149]
[0.61238756 0.55661814 0.58671487 0.6149414  0.62230551]

 87%|███████████████████████████████████████████████████████████████████████           | 26/30 [00:07<00:01,  3.57it/s]

[0.61221174 0.55655531 0.58655355 0.61470797 0.62191807]
[0.61507811 0.56420328 0.59213133 0.61499675 0.62759845]
[0.61497194 0.56271523 0.59152125 0.61542866 0.6271023 ]
[0.61473405 0.56088714 0.59070399 0.61575474 0.62642361]
[0.61433147 0.55864037 0.58963073 0.61594192 0.62551659]
[0.61371877 0.55683116 0.58823712 0.61594268 0.62431951]
[0.61290227 0.55671301 0.58723708 0.61568869 0.62327287]
[0.61270494 0.55670102 0.58701109 0.6153126  0.62292881]

 90%|█████████████████████████████████████████████████████████████████████████▊        | 27/30 [00:08<00:00,  3.44it/s]

[0.6125055  0.55666964 0.58679874 0.61508522 0.62254066]
[0.6123351  0.55661564 0.58664464 0.6148581  0.62214897]
[0.6121412  0.55654032 0.58646885 0.61460691 0.62173771]
[0.61507763 0.56416846 0.59209022 0.6150406  0.6275588 ]
[0.6149612  0.56263685 0.59145386 0.61547189 0.62703594]
[0.61470429 0.56074616 0.59059735 0.61578893 0.62631864]
[0.61427113 0.55841095 0.5894677  0.61595557 0.62535714]
[0.61361218 0.55682155 0.58799443 0.61591953 0.62408382]

 93%|████████████████████████████████████████████████████████████████████████████▌     | 28/30 [00:08<00:00,  3.53it/s]

[0.61287594 0.55673118 0.58718712 0.61560473 0.62317866]
[0.61266197 0.55671288 0.58694095 0.61523822 0.62281147]
[0.61246404 0.55667202 0.58673932 0.61501712 0.62240005]
[0.6122796  0.55661004 0.58657164 0.61477252 0.62198974]
[0.61207033 0.55652353 0.5863838  0.6145018  0.62155402]
[0.61507686 0.56413511 0.59204967 0.61508205 0.62751918]
[0.61495003 0.56256076 0.59138712 0.61551211 0.62696946]
[0.61467379 0.56060816 0.59049087 0.61581932 0.62621297]
[0.6142095  0.55818611 0.5893048  0.61596418 0.62519658]

 97%|███████████████████████████████████████████████████████████████████████████████▎  | 29/30 [00:08<00:00,  3.61it/s]

[0.61350341 0.55681077 0.58775089 0.61588934 0.62384598]
[0.61284789 0.55674774 0.58713463 0.61551153 0.62308265]
[0.61261715 0.55672287 0.58686845 0.6151791  0.62269153]
[0.61242025 0.55667365 0.58667763 0.61494539 0.62226202]
[0.61222122 0.55659971 0.58649593 0.6146836  0.62182782]
[0.61199591 0.55650307 0.58629197 0.61439265 0.62136699]
[0.61507583 0.56410317 0.59200966 0.61512123 0.62747961]
[0.61493846 0.56248731 0.59132102 0.61554949 0.6269029 ]

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.39it/s]

[0.61464313 0.56047305 0.59038534 0.61584604 0.62610716]
[0.6141467  0.55796465 0.5891421  0.61596805 0.62503501]
[0.61339259 0.55679903 0.58750704 0.61585304 0.62360577]
[0.61281733 0.55676139 0.58708061 0.61543782 0.62298507]
[0.61256896 0.556731   0.58679294 0.61512239 0.62256897]
[0.61237407 0.55667278 0.58661376 0.61487199 0.62212121]
[0.61215711 0.55658825 0.58642058 0.61459137 0.62166322]
[0.6119179  0.55647889 0.58619663 0.6142784  0.62117709]

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.29it/s]

        alpha  l1_ratio  cross_val_score
80   2.759345     0.001         0.602982
70   2.414552     0.001         0.602981
90   3.104138     0.001         0.602981
100  3.448931     0.001         0.602978
60   2.069759     0.001         0.602977

In [17]:
df_scores = pd.DataFrame(scores, columns=['alpha', 'l1_ratio', 'cross_val_score' ])
df_scores.sort_values(['cross_val_score'], ascending=False).head()

        alpha  l1_ratio  cross_val_score
80   2.759345     0.001         0.602982
70   2.414552     0.001         0.602981
90   3.104138     0.001         0.602981
100  3.448931     0.001         0.602978
60   2.069759     0.001         0.602977

### changing scoring parameter
#### `scoring` as RMSE

In [18]:
# from string_name_scores
alphas = np.linspace(0.001, 10, 30)
ratios = np.linspace(0.001,1,10) 
scores=[]
for a in tqdm(alphas):
    for r in ratios:
        el = ElasticNet(alpha=a, l1_ratio=r)
        results = cross_val_score(el, X, y, cv=kfold, scoring='neg_root_mean_squared_error')  # why 'neg': optimizer uses bigger the better in negative way
        scores.append([a, r, np.mean(results)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'l1_ratio', 'root_mean_squared_error' ])
df_scores.sort_values(['root_mean_squared_error'], ascending=False).head()

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.57it/s]

        alpha  l1_ratio  root_mean_squared_error
90   3.104138     0.001               -10.456384
100  3.448931     0.001               -10.456385
80   2.759345     0.001               -10.456410
110  3.793724     0.001               -10.456410
120  4.138517     0.001               -10.456456

In [19]:
features = [2,3,4,5,6,7]
scores=[]

for f in features:
    rf = RandomForestRegressor(random_state=26, max_features=f )
    results = cross_val_score(rf, X, y, cv=kfold, scoring='neg_root_mean_squared_error') 
    scores.append([f, np.mean(results)])
df_scores = pd.DataFrame(scores, columns=['features', 'root_mean_squared_error' ])
df_scores.sort_values(['root_mean_squared_error'], ascending=False).head()

   features  root_mean_squared_error
2         4                -4.751942
3         5                -4.754536
4         6                -4.790249
1         3                -4.794503
5         7                -4.814700

# Housing

In [21]:
housing = pd.read_csv('D:/Machine_Learning/Datasets/Housing.csv')
X , y = housing.drop(['price'], axis=1), housing['price']

In [33]:
# to increase the speed remove sparse_output, set_output

# ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
# trans = ColumnTransformer(transformers=[("OHE", ohe, make_column_selector(dtype_include=object))],     
#                           remainder="passthrough",verbose_feature_names_out=False).set_output(transform="pandas")

ohe=OneHotEncoder(drop="first")

trans = ColumnTransformer(transformers=[("OHE", ohe, make_column_selector(dtype_include=object))],     
                          remainder="passthrough", verbose_feature_names_out=False)

In [34]:
features = [2,3,4,5,6,7]
scores=[]

for f in tqdm(features):
    rf = RandomForestRegressor(random_state=26, max_features=f )
    pipe = Pipeline([('OHE',trans), ('RF',rf)])
    results = cross_val_score(pipe, X, y, cv=kfold, scoring='neg_root_mean_squared_error') 
    scores.append([f, np.mean(results)])
df_scores = pd.DataFrame(scores, columns=['features', 'root_mean_squared_error' ])
df_scores.sort_values(['root_mean_squared_error'], ascending=False).head()

100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:06<00:00,  1.03s/it]

   features  root_mean_squared_error
1         3            -16204.207742
0         2            -16284.461884
3         5            -16338.488053
2         4            -16530.071722
4         6            -16686.581621