In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from tqdm import tqdm
from sklearn.cluster import KMeans

In [3]:
rfm = pd.read_csv("Cases/Recency Frequency Monetary/rfm_data_customer.csv", index_col=0)
rfm

             revenue most_recent_visit  number_of_orders  recency_days
customer_id
22086            777        2006-05-14                 9           232
2290            1555        2006-09-08                16           115
26377            336        2006-11-19                 5            43
24650           1189        2006-10-29                12            64
12883           1229        2006-12-09                12            23
...              ...               ...               ...           ...
3249             998        2006-12-01                10            31
6686             771        2006-06-28                 8           187
16418           1016        2006-07-31                 9           154
9117             678        2006-06-20                 7           195
19184           1519        2006-09-10                13           113

[39999 rows x 4 columns]

In [12]:
rfm = rfm.drop('most_recent_visit', axis=1)

In [14]:
scaler = StandardScaler().set_output(transform='pandas')
df_scaled = scaler.fit_transform(rfm)
Ks = [2,3,4,5]
scores= []
for i in Ks:
    clust = KMeans(n_clusters=i, random_state=26)
    clust.fit(df_scaled)
    scores.append([i, silhouette_score(df_scaled, clust.labels_)])

df_scores = pd.DataFrame(scores, columns=['clusters', 'scores'])
df_scores.sort_values('scores', ascending=False)

   clusters    scores
1         3  0.370431
0         2  0.361962
3         5  0.325342
2         4  0.322671

### Cluster Analysis

In [21]:
km = KMeans(n_clusters=3, random_state=26)
km.fit(df_scaled)

df = rfm.copy() 
df['Cluster'] = km.labels_

df.groupby('Cluster').mean()

             revenue  number_of_orders  recency_days
Cluster
0        1285.523074         12.946774    133.283215
1         691.357762          7.343554    414.954233
2         753.347135          8.265399    135.530745

In [23]:
prcomp= PCA().set_output(transform='pandas')
df_scaled = scaler.fit_transform(df)
pca_data = prcomp.fit_transform(df_scaled)
km = KMeans(n_clusters=3, random_state=26)
km.fit(df_scaled)
pca_data['cluster'] = km.labels_
pca_data['cluster'] = pca_data['cluster'].astype('str')