In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder , StandardScaler
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import recall_score, precision_score, classification_report, roc_auc_score, log_loss

from sklearn.neighbors import KNeighborsClassifier

import os
os.chdir("D:/Machine_Learning/Cases") #fetch the dataset from the folder

In [2]:
sonar = pd.read_csv('D:/Machine_Learning/Cases/Sonar/Sonar.csv')
sonar.head()

       V1      V2      V3      V4      V5      V6      V7  ...     V55     V56     V57     V58     V59     V60  Class
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  ...  0.0072  0.0167  0.0180  0.0084  0.0090  0.0032      R
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  ...  0.0094  0.0191  0.0140  0.0049  0.0052  0.0044      R
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  ...  0.0180  0.0244  0.0316  0.0164  0.0095  0.0078      R
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  ...  0.0085  0.0073  0.0050  0.0044  0.0040  0.0117      R
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  ...  0.0110  0.0015  0.0072  0.0048  0.0107  0.0094      R

[5 rows x 61 columns]

In [7]:
le = LabelEncoder()
sonar['Class'] = le.fit_transform(sonar['Class'])
X , y = sonar.drop('Class', axis=1), sonar['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

In [16]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# accuracy_score(y_test, y_pred)
y_pred_prob = knn.predict_proba(X_test)
roc_auc_score(y_test, y_pred_prob[:,1])

0.8316430020283976

In [18]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_prob = knn.predict_proba(X_test)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
1   2  0.892495
2   3  0.881846
3   4  0.869168
4   5  0.845335
5   6  0.831643
6   7  0.809331
0   1  0.808316
7   8  0.790568
8   9  0.785497
9  10  0.761156

### HR Dataset

In [20]:
os.chdir("D:/Machine_Learning/Cases")
hr = pd.read_csv("HR_comma_sep.csv")
hr

       satisfaction_level  last_evaluation  number_project  ...  promotion_last_5years  Department  salary
0                    0.38             0.53               2  ...                      0       sales     low
1                    0.80             0.86               5  ...                      0       sales  medium
2                    0.10             0.77               6  ...                      0       sales     low
3                    0.92             0.85               5  ...                      0       sales     low
4                    0.89             1.00               5  ...                      0       sales     low
...                   ...              ...             ...  ...                    ...         ...     ...
14990                0.40             0.57               2  ...                      0     support     low
14991                0.37             0.48               2  ...                      0     support     low
14992                0.37             0.53               2  ...                      0     support     low
14993                0.11             0.96               6  ...                      0     support     low
14994                0.37             0.52               2  ...                      0     support     low

[14995 rows x 10 columns]

In [21]:
X = hr.drop('left',axis=1)
y=hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=hr['left'])

In [26]:
from sklearn.compose import make_column_selector

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")

trans = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))], remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [27]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [28]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict_proba(X_tst_ohe)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
7   8  0.973812
8   9  0.973488
6   7  0.973273
9  10  0.972681
5   6  0.972560
4   5  0.971581
3   4  0.970761
2   3  0.967524
1   2  0.963435
0   1  0.951201

### Image Segmentation Data (MultiClass)

In [29]:
os.chdir("D:/Machine_Learning/Cases/Image_Segmentation") #fetch the dataset from the folder
img = pd.read_csv("Image_Segmentation.csv")
img

         Class  region.centroid.col  region.centroid.row  ...  value.mean  saturation.mean  hue-mean
0    BRICKFACE                  188                  133  ...    8.444445         0.538580 -0.924817
1    BRICKFACE                  105                  139  ...    7.555555         0.532628 -0.965946
2    BRICKFACE                   34                  137  ...    7.777778         0.573633 -0.744272
3    BRICKFACE                   39                  111  ...    7.888889         0.562919 -1.175773
4    BRICKFACE                   16                  128  ...    7.111111         0.561508 -0.985811
..         ...                  ...                  ...  ...         ...              ...       ...
204      GRASS                   36                  243  ...   18.000000         0.452229  2.368311
205      GRASS                  186                  218  ...   17.777779         0.401347  2.382684
206      GRASS                  197                  236  ...   18.555555         0.292729  2.789800
207      GRASS                  208                  240  ...   18.555555         0.421621  2.392487
208      GRASS                  223                  185  ...   17.555555         0.445418  1.838850

[209 rows x 20 columns]

In [32]:
le = LabelEncoder()
img['Class'] = le.fit_transform(img['Class'])

X = img.drop('Class',axis=1)
y=img['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=img['Class'])

In [38]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_prob = knn.predict_proba(X_test)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)  # Best one should be the lowest one

   Ks  LogLoss score
5   6       0.971258
6   7       0.981489
7   8       1.016964
8   9       1.049631
9  10       1.084273
4   5       1.506703
2   3       1.996419
3   4       2.015082
1   2       3.036645
0   1       4.004850

## With Standard Sclaing

In [50]:
scaler = StandardScaler().set_output(transform="pandas")
# scaler.fit_transform()

In [51]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [59]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)

   Ks  LogLoss score
2   3       0.165250
3   4       0.197000
4   5       0.256929
5   6       0.281758
6   7       0.304352
7   8       0.343368
8   9       0.385612
9  10       0.400394
1   2       2.332495
0   1       2.860607

### Using MinMax Scaler

In [53]:
from sklearn.preprocessing import MinMaxScaler

In [57]:
scaler = MinMaxScaler().set_output(transform="pandas")
scaler

MinMaxScaler()

In [58]:
scaler.fit(X_train)   # min and max of every column get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)
X_trn_scl

     region.centroid.col  region.centroid.row  region.pixel.count  ...  value.mean  saturation.mean  hue-mean
94              0.143426             0.280335                 0.0  ...    0.343888         0.258916  0.119513
36              0.079681             0.330544                 0.0  ...    0.851988         0.179697  0.080272
16              0.087649             0.309623                 0.0  ...    0.145066         0.399751  0.212029
91              0.537849             0.142259                 0.0  ...    0.422680         0.259367  0.089892
108             0.593625             0.615063                 0.0  ...    0.081001         0.503086  0.108880
..                   ...                  ...                 ...  ...         ...              ...       ...
38              0.482072             0.000000                 0.0  ...    1.000000         0.092773  0.001724
136             0.884462             0.213389                 0.0  ...    0.075847         0.670370  0.089371
85              0.231076             0.456067                 0.0  ...    0.219440         0.681266  0.055540
148             0.354582             0.514644                 0.0  ...    0.030928         0.881481  0.095963
61              0.175299             0.326360                 0.0  ...    0.042710         0.986111  0.075436

[146 rows x 19 columns]

In [56]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)

   Ks  LogLoss score
2   3       0.165250
3   4       0.197000
4   5       0.256929
5   6       0.281758
6   7       0.304352
7   8       0.343368
8   9       0.385612
9  10       0.400394
1   2       2.332495
0   1       2.860607