In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import  ColumnTransformer, make_column_transformer, make_column_selector
from sklearn.metrics import r2_score, log_loss, accuracy_score, roc_auc_score, log_loss, root_mean_squared_error

from sklearn.tree import DecisionTreeRegressor, plot_tree, DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression, ElasticNet
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.ensemble import VotingClassifier, VotingRegressor

from tqdm import tqdm  # Provides the progress of model running
import os
os.chdir("C:/Users/PGCP-AI/Downloads/PredictingRoadAccident")

In [2]:
train = pd.read_csv('train.csv',index_col=0)
test = pd.read_csv('test.csv',index_col=0)
train

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
id,,,,,,,,,,,,,
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,highway,4,0.10,70,daylight,foggy,True,True,afternoon,False,False,2,0.32
517750,rural,4,0.47,35,daylight,rainy,True,True,morning,False,False,1,0.26
517751,urban,4,0.62,25,daylight,foggy,False,False,afternoon,False,True,0,0.19
517752,highway,3,0.63,25,night,clear,True,False,afternoon,True,True,3,0.51
517753,highway,2,0.31,45,dim,rainy,False,True,afternoon,True,True,2,0.22

In [28]:
X , y = train.drop('accident_risk', axis=1), train['accident_risk']
X_trn_ohe = trans.fit_transform(X)
X_tst_ohe = trans.transform(test)

In [30]:
lr = LinearRegression()
lr.fit(X_trn_ohe, y)

y_pred = lr.predict(X_tst_ohe)
y_pred[y_pred<0]=0
y_pred.min(), y_pred.max()

(np.float64(0.0), np.float64(0.8596132989017367))

In [31]:

submit = pd.read_csv("sample_submission.csv")
submit['accident_risk']=y_pred
submit.to_csv("sbt_lnr_22_4.csv", index=False)

In [32]:
submit

            id  accident_risk
0       517754       0.365056
1       517755       0.157263
2       517756       0.208640
3       517757       0.436072
4       517758       0.329073
...        ...            ...
172580  690334       0.180574
172581  690335       0.542430
172582  690336       0.243033
172583  690337       0.171115
172584  690338       0.485187

[172585 rows x 2 columns]